import { Firm, Call } from './types';

export const demoFirms: Firm[] = [
  {id:'f01',name:'Mazars LLP',ch_number:'03544199',city:'London',region:'London',size:'Large (50+)',staff_count:'650',contact_name:'James Porter',contact_title:'Head of Operations',phone:'0207 063 4100',email:'j.porter@mazars.co.uk',main_phone:'0207 063 4000',category:'',source:'Data mining',stage:'Win',pricing_model:'PAYG',service_interest:'Bookkeeping & VAT',assigned_to:'Diksha',last_contact:'2026-03-10',follow_up:'',notes:'Won PAYG contract — 450 hrs/year. James was the key decision maker, pushed back initially on cost but agreed once we showed time saving calculations. Contract signed March 2026. Very happy with onboarding.',win_amount:4500,added_date:'2026-01-15',website:'www.mazars.co.uk',linkedin:'linkedin.com/company/mazars',contact_li:'linkedin.com/in/james-porter-mazars'},
  {id:'f02',name:'Crowe UK LLP',ch_number:'02214226',city:'Manchester',region:'North West',size:'Mid (11–50)',staff_count:'48',contact_name:'Priya Patel',contact_title:'Managing Partner',phone:'0161 214 7542',email:'p.patel@crowe.co.uk',main_phone:'0161 214 7500',category:'',source:'Data mining',stage:'Win',pricing_model:'FTE',service_interest:'Payroll',assigned_to:'Sadichha',last_contact:'2026-02-20',follow_up:'',notes:'FTE pilot started Feb 2026. Priya very engaged — wants to expand to personal tax in Q3. 2 staff placed (Deepa + Raj). Monthly review call every 3rd Wednesday.',win_amount:2700,added_date:'2026-01-18',website:'www.crowe.co.uk',linkedin:'linkedin.com/company/crowe-uk',contact_li:'linkedin.com/in/priya-patel-crowe'},
  {id:'f03',name:'Menzies LLP',ch_number:'01868736',city:'Guildford',region:'South East',size:'Mid (11–50)',staff_count:'38',contact_name:'Andrew Nash',contact_title:'Managing Director',phone:'01483 565800',email:'a.nash@menzies.co.uk',main_phone:'01483 565765',category:'',source:'LinkedIn',stage:'Proposal',pricing_model:'Both discussed',service_interest:'Full package',assigned_to:'Diksha',last_contact:'2026-03-23',follow_up:'2026-03-28',notes:'Proposal sent 23 March. Andrew is comparing us vs a freelancer. Key pain: VAT filing bottleneck in Jan–Mar. He liked the PAYG flexibility. Follow up Friday — board meet Thursday so decision likely next week. Price sensitivity is moderate.',win_amount:0,added_date:'2026-01-22',website:'www.menzies.co.uk',linkedin:'linkedin.com/company/menzies-llp',contact_li:'linkedin.com/in/andrew-nash-menzies'},
  {id:'f04',name:'PKF Littlejohn LLP',ch_number:'01116649',city:'London',region:'London',size:'Mid (11–50)',staff_count:'42',contact_name:'David Chen',contact_title:'Finance Director',phone:'0207 516 2244',email:'d.chen@pkf.co.uk',main_phone:'0207 516 2200',category:'',source:'Data mining',stage:'Proposal',pricing_model:'PAYG',service_interest:'Personal Tax & Year-End',assigned_to:'Sadichha',last_contact:'2026-03-21',follow_up:'2026-03-29',notes:'Demo done 21 March — David very impressed with turnaround time SLA. Proposal for 450hr PAYG bundle sent same day. Waiting on sign-off from their CEO (Helen Park). David says likely yes but needs 2 weeks. Key objection was data security — sent them our ISO cert.',win_amount:0,added_date:'2026-01-25',website:'www.pkf.co.uk',linkedin:'linkedin.com/company/pkf-littlejohn',contact_li:'linkedin.com/in/david-chen-pkf'},
  {id:'f05',name:'haysmacintyre',ch_number:'02128261',city:'London',region:'London',size:'Mid (11–50)',staff_count:'35',contact_name:'Claire Ford',contact_title:'Partner — Private Client',phone:'0207 969 5522',email:'c.ford@haysmac.co.uk',main_phone:'0207 969 5500',category:'',source:'LinkedIn',stage:'Suspect',pricing_model:'FTE',service_interest:'Personal Tax & Year-End',assigned_to:'Diksha',last_contact:'2026-03-20',follow_up:'2026-03-27',notes:'Connected on LinkedIn March 10. Claire responded positively — interested in FTE for personal tax season (Jan-Apr peak). Gatekeeper issue on direct line — use LinkedIn DM or email only. She mentioned they had a bad experience with an overseas provider in 2024, so needs trust-building first. Suggested a coffee meeting.',win_amount:0,added_date:'2026-02-03',website:'www.haysmacintyre.com',linkedin:'linkedin.com/company/haysmacintyre',contact_li:'linkedin.com/in/claire-ford-hays'},
  {id:'f06',name:'Armstrong Watson',ch_number:'00872891',city:'Leeds',region:'Yorkshire',size:'SME (1–10)',staff_count:'9',contact_name:'Michael Stone',contact_title:'Senior Partner',phone:'0113 200 3842',email:'m.stone@armstrongwatson.co.uk',main_phone:'0113 200 3800',category:'',source:'Data mining',stage:'Lead',pricing_model:'',service_interest:'Bookkeeping & VAT',assigned_to:'Sadichha',last_contact:'2026-03-19',follow_up:'2026-03-26',notes:'Cold called 3 times. Got through once — Michael listened but said not the right time. They are in the middle of a partner reshuffle. Try again end of April. He did say VAT filing is a pain point. Left voicemail with callback number. Flag for Q2 push.',win_amount:0,added_date:'2026-02-05',website:'www.armstrongwatson.co.uk',linkedin:'linkedin.com/company/armstrong-watson',contact_li:''},
  {id:'f07',name:'Buzzacott LLP',ch_number:'01687373',city:'London',region:'London',size:'SME (1–10)',staff_count:'8',contact_name:'Rachel Adams',contact_title:'Director of Finance',phone:'0207 556 1244',email:'r.adams@buzzacott.co.uk',main_phone:'0207 556 1200',category:'',source:'LinkedIn',stage:'Suspect',pricing_model:'FTE',service_interest:'Bookkeeping & VAT',assigned_to:'Diksha',last_contact:'2026-03-18',follow_up:'2026-03-25',notes:'Very warm lead. Rachel reached out to us on LinkedIn after seeing a post. Budget approved for FTE pilot. She wants 1 dedicated resource for bookkeeping + VAT. Meeting booked 2 April 10am at their Holborn office. Send confirmation + prep pack by 28 March.',win_amount:0,added_date:'2026-02-08',website:'www.buzzacott.co.uk',linkedin:'linkedin.com/company/buzzacott',contact_li:'linkedin.com/in/rachel-adams-buzzacott'},
  {id:'f08',name:'Wilkins Kennedy',ch_number:'00497681',city:'London',region:'London',size:'SME (1–10)',staff_count:'9',contact_name:'Frances Wu',contact_title:'Practice Manager',phone:'0207 306 9144',email:'f.wu@wilkinskennedy.com',main_phone:'0207 306 9100',category:'',source:'SEO / Inbound',stage:'Win',pricing_model:'PAYG',service_interest:'Bookkeeping & VAT',assigned_to:'Sadichha',last_contact:'2026-02-14',follow_up:'',notes:'Inbound enquiry from website. Frances already knew DiTech from referral (Bishop Fleming). Closed in 2 calls — no hard sell needed. PAYG 450hr contract. Frances is a champion — has mentioned us to 2 other firms already. Ask for referral formally in April review.',win_amount:3800,added_date:'2026-01-30',website:'www.wilkinskennedy.com',linkedin:'linkedin.com/company/wilkins-kennedy',contact_li:'linkedin.com/in/frances-wu-wk'},
  {id:'f09',name:'FRP Advisory',ch_number:'06032782',city:'London',region:'London',size:'Large (50+)',staff_count:'210',contact_name:'Marcus Bell',contact_title:'Partner — Corporate Finance',phone:'0207 036 0955',email:'m.bell@frpadvisory.com',main_phone:'0207 036 0990',category:'',source:'Event',stage:'Proposal',pricing_model:'PAYG',service_interest:'Personal Tax & Year-End',assigned_to:'Diksha',last_contact:'2026-03-15',follow_up:'2026-03-28',notes:'Met Marcus at Accountex ExCeL 23 Oct. Good conversation at the stand — he took our brochure and followed up himself. Long sales cycle expected (large firm, procurement process). Proposal submitted for 450hr PAYG for personal tax season. Key contact in procurement: Sarah Yates (s.yates@frpadvisory.com). Decision before April.',win_amount:0,added_date:'2026-01-10',website:'www.frpadvisory.com',linkedin:'linkedin.com/company/frp-advisory',contact_li:'linkedin.com/in/marcus-bell-frp'},
  {id:'f10',name:'Xeinadin Group',ch_number:'11854152',city:'Birmingham',region:'Midlands',size:'Large (50+)',staff_count:'320',contact_name:'Carlos Reyes',contact_title:'Chief Operating Officer',phone:'0121 555 0144',email:'c.reyes@xeinadin.co.uk',main_phone:'0121 555 0100',category:'',source:'Data mining',stage:'Win',pricing_model:'FTE',service_interest:'Full package',assigned_to:'Sadichha',last_contact:'2026-03-05',follow_up:'2026-04-15',notes:'3 FTE staff placed since Jan 2026 — Amara (bookkeeping), Dev (payroll), Lena (personal tax). Carlos is very satisfied. Monthly review call booked. Expansion discussion in April — they want to potentially add 2 more FTE for year-end season. Key risk: Carlos leaving (hinted at move). Establish secondary contact.',win_amount:2700,added_date:'2025-12-10',website:'www.xeinadin.com',linkedin:'linkedin.com/company/xeinadin',contact_li:'linkedin.com/in/carlos-reyes-xeinadin'},
  {id:'f11',name:'Bishop Fleming',ch_number:'02780952',city:'Bristol',region:'South West',size:'Mid (11–50)',staff_count:'32',contact_name:'Natalie Groves',contact_title:'Tax Manager',phone:'0117 910 0175',email:'n.groves@bishopfleming.co.uk',main_phone:'0117 910 0100',category:'',source:'Referral',stage:'Suspect',pricing_model:'PAYG',service_interest:'Personal Tax & Year-End',assigned_to:'Diksha',last_contact:'2026-03-12',follow_up:'2026-04-01',notes:'Referred by Frances Wu at Wilkins Kennedy. Natalie already briefed on DiTech — warm intro. She is evaluating for Q2 tax season. Send case study deck. First call went well — no hard objections, just needs to see numbers. Budget approx £3–5k.',win_amount:0,added_date:'2026-02-20',website:'www.bishopfleming.co.uk',linkedin:'linkedin.com/company/bishop-fleming',contact_li:'linkedin.com/in/natalie-groves-bf'},
  {id:'f12',name:'Saffery LLP',ch_number:'05592547',city:'London',region:'London',size:'Large (50+)',staff_count:'180',contact_name:'Tom Whitfield',contact_title:'Director of Operations',phone:'0207 841 4163',email:'t.whitfield@saffery.com',main_phone:'0207 841 4000',category:'',source:'Data mining',stage:'Lead',pricing_model:'',service_interest:'Bookkeeping & VAT',assigned_to:'Sadichha',last_contact:'2026-03-22',follow_up:'2026-03-29',notes:'Cold call — Tom picked up, was polite but short. Said to send an email with details, he would pass to the relevant partner. Email sent same day with intro deck. No response yet. Chase by email 29 March. Large firm so will need partner sign-off.',win_amount:0,added_date:'2026-02-25',website:'www.saffery.com',linkedin:'linkedin.com/company/saffery-champness',contact_li:''},
  {id:'f13',name:'MHA MacIntyre Hudson',ch_number:'00603062',city:'London',region:'London',size:'Large (50+)',staff_count:'250',contact_name:'Geeta Sharma',contact_title:'Head of People & Ops',phone:'0207 429 4165',email:'g.sharma@mha.co.uk',main_phone:'0207 429 4100',category:'',source:'LinkedIn',stage:'Suspect',pricing_model:'FTE',service_interest:'Payroll',assigned_to:'Diksha',last_contact:'2026-03-17',follow_up:'2026-03-31',notes:'LinkedIn connection — Geeta active on HR/ops content. Commented on a DiTech post. DM conversation ongoing. She is exploring outsourced payroll options as they scale. Internal politics: partner group is cautious. Geeta is a champion but needs senior sponsor. Suggested inviting her partner (Ben Lee) to a demo call.',win_amount:0,added_date:'2026-03-01',website:'www.mha.co.uk',linkedin:'linkedin.com/company/mha-international',contact_li:'linkedin.com/in/geeta-sharma-mha'},
  {id:'f14',name:'Begbies Traynor',ch_number:'02575540',city:'Manchester',region:'North West',size:'Large (50+)',staff_count:'95',contact_name:'Alan Griffiths',contact_title:'Partner',phone:'0161 837 1700',email:'a.griffiths@begbies-traynor.com',main_phone:'0161 837 1700',category:'',source:'Event',stage:'Lead',pricing_model:'',service_interest:'Bookkeeping & VAT',assigned_to:'Sadichha',last_contact:'2026-03-08',follow_up:'2026-04-05',notes:'Met at Northern Accountancy Summit March 8. Alan dropped his card and said call him. Called twice — got through once, he is interested but swamped until after Easter. Push to April pipeline.',win_amount:0,added_date:'2026-03-08',website:'www.begbies-traynor.com',linkedin:'linkedin.com/company/begbies-traynor-group',contact_li:''},
  {id:'f15',name:'Leonard Curtis',ch_number:'05120671',city:'Manchester',region:'North West',size:'SME (1–10)',staff_count:'6',contact_name:'Sophie Brennan',contact_title:'Office Manager',phone:'0161 214 0000',email:'s.brennan@leonardcurtis.co.uk',main_phone:'0161 214 0000',category:'',source:'Data mining',stage:'Lost',pricing_model:'',service_interest:'',assigned_to:'Sadichha',last_contact:'2026-02-28',follow_up:'',notes:'Spoke to Sophie — they outsourced to a local bookkeeper in January (long-term relationship). Not the right time. Mark as lost for now. Re-contact in 12 months or if their situation changes.',win_amount:0,added_date:'2026-01-20',website:'www.leonardcurtis.co.uk',linkedin:'linkedin.com/company/leonard-curtis',contact_li:''},
];

export const getDemoCalls = (): Call[] => {
  const T = () => new Date();
  const daysAgo = (n: number, h: number, m: number) => {
    const d = new Date(T().getTime() - n * 86400000);
    d.setHours(h, m, 0, 0);
    return d.toISOString();
  };
  
  const calls: Call[] = [
    // TODAY
    {id:'dc01',rep:'Diksha',firm:'Menzies LLP',firmId:'f03',contact:'Andrew Nash',type:'followup',oc:'mtg',stage:'Proposal',notes:'Confirmed meeting for Tuesday 1 April 2pm. Andrew has board approval to proceed — just needs final sign-off on contract. Very positive. Mentioned they had a bad run with offshore team before so trust is key.',fu:'2026-04-01',mtgDate:'2026-04-01',ts:daysAgo(0,9,14)},
    {id:'dc02',rep:'Diksha',firm:'haysmacintyre',firmId:'f05',contact:'Reception / Gatekeeper',type:'call',oc:'gk',stage:'',notes:'Claire not available again. Reception says she is in client meetings all week. Going to try LinkedIn DM and direct email instead of the main line.',fu:daysAgo(0,0,0).split('T')[0],mtgDate:'',ts:daysAgo(0,9,44)},
    {id:'dc03',rep:'Sadichha',firm:'Armstrong Watson',firmId:'f06',contact:'Michael Stone',type:'call',oc:'cb',stage:'',notes:'Michael answered — said he has 15 minutes next Tuesday morning (1 April, 9am). Calendar invite sent. He mentioned the partner reshuffle is nearly done so timing might actually be good now.',fu:'2026-04-01',mtgDate:'',ts:daysAgo(0,10,2)},
    {id:'dc04',rep:'Diksha',firm:'PKF Littlejohn LLP',firmId:'f04',contact:'David Chen',type:'followup',oc:'in',stage:'Proposal',notes:'David chased us! He says Helen Park has reviewed the proposal and has one question about the data hosting location. Sent our UK-hosted infrastructure doc. He expects a decision by end of next week.',fu:'2026-04-04',mtgDate:'',ts:daysAgo(0,10,31)},
    {id:'dc05',rep:'Sadichha',firm:'FRP Advisory',firmId:'f09',contact:'Marcus Bell',type:'followup',oc:'in',stage:'Proposal',notes:'Marcus confirmed Sarah Yates in procurement has the proposal. She will review by 28 March. Marcus sounded confident — says the budget is there and they want to start before April year-end.',fu:'2026-03-28',mtgDate:'',ts:daysAgo(0,11,8)},
    {id:'dc06',rep:'Diksha',firm:'Buzzacott LLP',firmId:'f07',contact:'Rachel Adams',type:'followup',oc:'mtg',stage:'Suspect',notes:'Rachel confirmed 2 April meeting at Holborn office, 10am. She wants to bring her senior bookkeeper to the call as well. Prep pack sent. Very warm — she already has a preferred start date of 1 May.',fu:'',mtgDate:'2026-04-02',ts:daysAgo(0,11,25)},
    {id:'dc07',rep:'Sadichha',firm:'Saffery LLP',firmId:'f12',contact:'Tom Whitfield',type:'call',oc:'na',stage:'',notes:'No answer on direct line. Left voicemail. Will try tomorrow at different time.',fu:daysAgo(0,0,0).split('T')[0],mtgDate:'',ts:daysAgo(0,11,52)},
    {id:'dc08',rep:'Diksha',firm:'MHA MacIntyre Hudson',firmId:'f13',contact:'Geeta Sharma',type:'linkedin',oc:'in',stage:'Suspect',notes:'Geeta replied to DM — she has spoken to Ben Lee (partner) and he is open to a 30min intro call. She asked for a Zoom link. Sent calendar link for w/c 31 March.',fu:'2026-03-31',mtgDate:'2026-03-31',ts:daysAgo(0,12,15)},
    {id:'dc09',rep:'Sadichha',firm:'Bishop Fleming',firmId:'f11',contact:'Natalie Groves',type:'followup',oc:'cb',stage:'Suspect',notes:'Natalie reviewed the case study pack. Wants a 20-min call to discuss numbers before going to her partner. Agreed on Thursday 27 March 3pm.',fu:'2026-03-27',mtgDate:'',ts:daysAgo(0,14,5)},
    {id:'dc10',rep:'Diksha',firm:'Begbies Traynor',firmId:'f14',contact:'Alan Griffiths',type:'call',oc:'vm',stage:'',notes:'Left voicemail — mentioned our conversation at the Summit. Asked him to call back or email when back from Easter. Number confirmed on CH website.',fu:'2026-04-07',mtgDate:'',ts:daysAgo(0,14,38)},
    // YESTERDAY
    {id:'dc11',rep:'Diksha',firm:'Menzies LLP',firmId:'f03',contact:'Andrew Nash',type:'followup',oc:'in',stage:'Proposal',notes:'Called to check he received the proposal PDF. He did — said it looks good and is aligned with their budget. Board review Thursday.',fu:'2026-03-24',mtgDate:'',ts:daysAgo(1,9,30)},
    {id:'dc12',rep:'Sadichha',firm:'PKF Littlejohn LLP',firmId:'f04',contact:'David Chen',type:'email',oc:'in',stage:'',notes:'Followed up proposal email. David replied within the hour — he is pushing internally. Good sign.',fu:'2026-03-27',mtgDate:'',ts:daysAgo(1,10,0)},
    {id:'dc13',rep:'Diksha',firm:'haysmacintyre',firmId:'f05',contact:'Claire Ford',type:'linkedin',oc:'in',stage:'Suspect',notes:'LinkedIn DM — Claire responded! She said she is free for a call Monday 31 March 11am. Calendar invite sent immediately.',fu:'2026-03-31',mtgDate:'2026-03-31',ts:daysAgo(1,11,15)},
    {id:'dc14',rep:'Sadichha',firm:'Armstrong Watson',firmId:'f06',contact:'Receptionist',type:'call',oc:'na',stage:'',notes:'No answer on main line. Tried twice at 10am and 2pm.',fu:daysAgo(0,0,0).split('T')[0],mtgDate:'',ts:daysAgo(1,14,0)},
    {id:'dc15',rep:'Diksha',firm:'Bishop Fleming',firmId:'f11',contact:'Natalie Groves',type:'call',oc:'in',stage:'Suspect',notes:'First full pitch call. Natalie asked good questions about turnaround times and SLA. Sent case study after call.',fu:'2026-03-27',mtgDate:'',ts:daysAgo(1,15,30)},
    {id:'dc16',rep:'Sadichha',firm:'Saffery LLP',firmId:'f12',contact:'Tom Whitfield',type:'email',oc:'in',stage:'',notes:'Tom replied to intro email — said he would forward to relevant partner (Janet Holt) who handles outsourcing decisions.',fu:'2026-03-29',mtgDate:'',ts:daysAgo(1,16,0)},
    // 3 DAYS AGO
    {id:'dc17',rep:'Diksha',firm:'FRP Advisory',firmId:'f09',contact:'Marcus Bell',type:'followup',oc:'mtg',stage:'Proposal',notes:'Formal proposal meeting with Marcus and Sarah Yates (procurement). 1hr video call. Went well — Sarah had prepared questions about IR35 compliance and data security. Both answered on the call. They will revert by 28 March.',fu:'2026-03-28',mtgDate:'',ts:daysAgo(3,10,0)},
    {id:'dc18',rep:'Sadichha',firm:'Begbies Traynor',firmId:'f14',contact:'Alan Griffiths',type:'call',oc:'cb',stage:'',notes:'Got through — Alan sounded interested but really is too busy until after Easter. Confirmed April 7 as re-contact date.',fu:'2026-04-07',mtgDate:'',ts:daysAgo(3,11,30)},
    {id:'dc19',rep:'Diksha',firm:'Menzies LLP',firmId:'f03',contact:'Andrew Nash',type:'meeting',oc:'mtg',stage:'Proposal',notes:'In-person meeting at Menzies Guildford office. Presented full solution. Andrew was engaged throughout — asked specifically about the Xero integration. He wants to run a 3-month trial before committing to annual.',fu:'2026-03-23',mtgDate:'',ts:daysAgo(3,14,0)},
    {id:'dc20',rep:'Sadichha',firm:'MHA MacIntyre Hudson',firmId:'f13',contact:'Geeta Sharma',type:'call',oc:'in',stage:'Suspect',notes:'Initial call went very well. Geeta outlined their payroll challenges — 3 different payroll systems across offices. She wants to consolidate and DiTech could be the solution.',fu:'2026-03-31',mtgDate:'',ts:daysAgo(3,15,0)},
    // LAST WEEK
    {id:'dc21',rep:'Diksha',firm:'PKF Littlejohn LLP',firmId:'f04',contact:'David Chen',type:'meeting',oc:'mtg',stage:'Proposal',notes:'Live demo via Teams. Walked through the portal and showed 3 sample client files. David was visibly impressed with the turnaround dashboard. Said this is exactly what they need. Proposal sent same evening.',fu:'2026-03-21',mtgDate:'',ts:daysAgo(6,10,0)},
    {id:'dc22',rep:'Sadichha',firm:'Bishop Fleming',firmId:'f11',contact:'Natalie Groves',type:'call',oc:'in',stage:'Suspect',notes:'First contact after referral from Frances Wu. Natalie already knew about DiTech — Frances had spoken highly of us. Very warm call — she asked for our deck and case studies.',fu:'2026-03-20',mtgDate:'',ts:daysAgo(7,11,0)},
    {id:'dc23',rep:'Diksha',firm:'Leonard Curtis',firmId:'f15',contact:'Sophie Brennan',type:'call',oc:'ni',stage:'Lost',notes:'Sophie confirmed they signed with a local bookkeeper in January — long-standing relationship. Not interested at this stage. Polite but firm.',fu:'',mtgDate:'',ts:daysAgo(14,10,30)},
  ];
  return calls;
};
